"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/utils/supabase/server";

// ── Upload File ──────────────────────────────────────────────────────────────

export type UploadState = {
  error?: string;
  jobId?: string;
};

const MOCK_MARKDOWN = `# Document Summary

This is a **mock conversion** output generated by RAG-Refine.

## Key Sections

### Section 1: Introduction
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

### Section 2: Main Content
- Point A: Data extraction with structural integrity
- Point B: Noise filtering and cleanup
- Point C: Semantic optimization for RAG

### Section 3: Conclusion
The document has been successfully converted to LLM-optimized Markdown format.

---
*Processed by RAG-Refine*
`;

export async function uploadFile(
  _prevState: UploadState | Record<string, never>,
  formData: FormData
): Promise<UploadState> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" };

  const file = formData.get("file") as File | null;
  const accountId = formData.get("account_id") as string | null;

  if (!file || !accountId) {
    return { error: "File and account are required." };
  }

  const allowedTypes = [
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "text/html",
  ];
  if (!allowedTypes.includes(file.type)) {
    return { error: "Unsupported file type. Use PDF, DOCX, or HTML." };
  }

  if (file.size > 50 * 1024 * 1024) {
    return { error: "File size exceeds 50MB limit." };
  }

  // Create job row (MVP: immediately completed with mock markdown)
  const { data: job, error: jobError } = await supabase
    .from("jobs")
    .insert({
      account_id: accountId,
      user_id: user.id,
      file_name: file.name,
      file_size: file.size,
      file_type: file.type,
      status: "completed",
      page_count: Math.ceil(file.size / 3000), // rough estimate
      output_markdown: MOCK_MARKDOWN,
    })
    .select("id")
    .single();

  if (jobError) {
    return { error: jobError.message };
  }

  // Upload file to Supabase Storage
  const storagePath = `${accountId}/${job.id}/${file.name}`;
  const arrayBuffer = await file.arrayBuffer();
  const { error: storageError } = await supabase.storage
    .from("documents")
    .upload(storagePath, arrayBuffer, {
      contentType: file.type,
      upsert: false,
    });

  if (storageError) {
    // Update job with storage path failure but keep the job
    await supabase
      .from("jobs")
      .update({ storage_path: null })
      .eq("id", job.id);
  } else {
    await supabase
      .from("jobs")
      .update({ storage_path: storagePath })
      .eq("id", job.id);
  }

  revalidatePath("/dashboard");
  return { jobId: job.id };
}

// ── Delete Job ───────────────────────────────────────────────────────────────

export type DeleteState = {
  error?: string;
};

export async function deleteJob(
  _prevState: DeleteState | Record<string, never>,
  formData: FormData
): Promise<DeleteState> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" };

  const jobId = formData.get("job_id") as string;
  if (!jobId) return { error: "Job ID is required." };

  // Fetch job to get storage path
  const { data: job } = await supabase
    .from("jobs")
    .select("storage_path")
    .eq("id", jobId)
    .single();

  // Delete from storage if path exists
  if (job?.storage_path) {
    await supabase.storage.from("documents").remove([job.storage_path]);
  }

  // Delete job row
  const { error } = await supabase.from("jobs").delete().eq("id", jobId);

  if (error) return { error: error.message };

  revalidatePath("/dashboard");
  return {};
}

// ── Generate API Key ─────────────────────────────────────────────────────────

export type ApiKeyState = {
  error?: string;
  key?: string;
};

export async function generateApiKey(
  _prevState: ApiKeyState | Record<string, never>,
  formData: FormData
): Promise<ApiKeyState> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" };

  const accountId = formData.get("account_id") as string;
  const label = (formData.get("label") as string) || "Default";

  if (!accountId) return { error: "Account is required." };

  // Generate a random API key with rr_ prefix
  const rawKey = crypto.randomUUID().replace(/-/g, "");
  const fullKey = `rr_${rawKey}`;
  const keyPrefix = fullKey.slice(0, 8);

  // Hash the key for storage
  const encoder = new TextEncoder();
  const data = encoder.encode(fullKey);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const keyHash = hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");

  const { error } = await supabase.from("api_keys").insert({
    account_id: accountId,
    user_id: user.id,
    key_prefix: keyPrefix,
    key_hash: keyHash,
    label,
  });

  if (error) return { error: error.message };

  revalidatePath("/dashboard");
  return { key: fullKey };
}

// ── Revoke API Key ───────────────────────────────────────────────────────────

export type RevokeState = {
  error?: string;
};

export async function revokeApiKey(
  _prevState: RevokeState | Record<string, never>,
  formData: FormData
): Promise<RevokeState> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated" };

  const keyId = formData.get("key_id") as string;
  if (!keyId) return { error: "Key ID is required." };

  const { error } = await supabase.from("api_keys").delete().eq("id", keyId);

  if (error) return { error: error.message };

  revalidatePath("/dashboard");
  return {};
}
